# Generated by Django 5.1 on 2024-08-14 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citizenship_number", models.CharField(max_length=20, unique=True)),
                ("issued_date", models.DateField()),
                ("issued_district", models.CharField(max_length=100)),
                ("pan_number", models.CharField(max_length=20, unique=True)),
                (
                    "pan_upload",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/pan/"
                    ),
                ),
                (
                    "citizenship_upload",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/citizenship/"
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_account", models.CharField(max_length=30, unique=True)),
                ("bank_account_name", models.CharField(max_length=100)),
                ("bank_branch", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=50, unique=True)),
                ("fingerprint_id", models.CharField(max_length=50, unique=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_info",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
